apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: task-tracker
  labels:
    app: web-frontend
spec:
  selector:
    app: web-frontend
  ports:
    - name: http
      port: 3005
      targetPort: 3005
