apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: task-tracker
  labels:
    app: progress-service
spec:
  selector:
    app: progress-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
