apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: task-tracker
  labels:
    app: alert-service
spec:
  selector:
    app: alert-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
